import type { ReactNode } from 'react'
import { NavLink } from 'react-router-dom'

const EMAIL = 'itskrutak@gmail.com'
const UPDATED = 'August 3, 2026'

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-mono font-bold text-accent-primary mb-2">{title}</h2>
      <div className="text-sm text-text-secondary leading-relaxed space-y-2">{children}</div>
    </section>
  )
}

export default function Terms({ onAccept }: { onAccept?: () => void } = {}) {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12">
      <h1 className="text-2xl font-mono font-bold text-text-primary mb-1">Terms of Service</h1>
      <p className="text-xs font-mono text-text-muted mb-10">
        {onAccept
          ? 'Please review and accept before using PromptGym.'
          : `Last updated: ${UPDATED}`}
      </p>

      <Section title="1. What PromptGym is">
        <p>
          PromptGym is a practice platform for timed AI-assisted coding challenges. You describe an
          app in a brief, an AI agent builds it in a sandbox under your direction, and an AI judge
          scores the result. The service is provided for educational and practice purposes.
        </p>
      </Section>

      <Section title="2. Acceptable use">
        <p>By using PromptGym you agree not to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>submit prompts intended to produce illegal, harmful, or malicious code;</li>
          <li>attempt to break out of, overload, or abuse the sandbox environment;</li>
          <li>circumvent rate limits, spend caps, or other technical safeguards;</li>
          <li>use the service to generate content that infringes others' rights.</li>
        </ul>
        <p>We may suspend access that threatens the stability or cost of the service.</p>
      </Section>

      <Section title="3. AI-generated content">
        <p>
          Code and text produced by the building agent and scores produced by the judge are
          generated by third-party large language models. They may be inaccurate, insecure, or
          unsuitable for production. You are responsible for reviewing anything you rely on. Scores
          are estimates for practice feedback only, not a professional assessment.
        </p>
      </Section>

      <Section title="4. Your content">
        <p>
          You retain ownership of the prompts you write and the app output generated from them. You
          grant us permission to process and store this content as needed to operate the service
          (running the sandbox, grading, and showing your history).
        </p>
      </Section>

      <Section title="5. Availability and data">
        <p>
          The service is provided "as is" without warranty of any kind. Sandboxes are ephemeral and
          may be destroyed after a challenge's time limit. We do not guarantee uptime, and we may
          change or discontinue features at any time.
        </p>
      </Section>

      <Section title="6. Limitation of liability">
        <p>
          To the maximum extent permitted by law, PromptGym and its operator are not liable for any
          indirect, incidental, or consequential damages arising from your use of the service,
          including any reliance on AI-generated code or scores.
        </p>
      </Section>

      <Section title="7. Changes to these terms">
        <p>
          We may update these terms from time to time. Continued use of the service after an update
          constitutes acceptance of the revised terms.
        </p>
      </Section>

      <Section title="8. Contact">
        <p>
          Questions about these terms? Reach us at{' '}
          <a href={`mailto:${EMAIL}`} className="text-accent-cyan hover:underline">
            {EMAIL}
          </a>
          .
        </p>
      </Section>

      {onAccept ? (
        <button className="btn-primary" onClick={onAccept}>
          I Agree — Enter PromptGym
        </button>
      ) : (
        <NavLink to="/" className="text-sm font-mono text-accent-primary hover:underline">
          ← Back to challenges
        </NavLink>
      )}
    </div>
  )
}
